set_device_attributes:
  description: Set the attributes of device.
  fields:
    device_id:
      description: Device ID
    attribute:
      description: The attribute want to set
      example: "eco_mode"
    value:
      description: The attribute value want to set
        example: True
